version: '3.8'

services:
  # PostgreSQL Service
  postgres:
    image: postgres:latest
    container_name: db_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: UserAdminSystem
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    restart: on-failure

  # Node.js App Service
  node_app:
    image: ramakant6520/user_admin_system_nodejs
    container_name: node_app
    environment:
      DB_HOST: postgres  # Use the service name 'postgres' as the hostname
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: UserAdminSystem
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - my_network
    restart: always

# Volumes
volumes:
  postgres_data:

# Networks
networks:
  my_network:
    driver: bridge
